# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install dependencies'

# Optional build step (won't fail if build script is missing)
- script: |
    if npm run | grep -q 'build'; then
      echo "Build script found. Running build..."
      npm run build
    else
      echo "No build script found. Skipping build step."
    fi
  displayName: 'Check and run build script'

# Publish artifact (adjust path based on your app's output)
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'  # Or a sub-folder like 'dist' if you generate build output
    artifact: 'nodejs-app'
    publishLocation: 'pipeline'
  displayName: 'Publish app artifact'
